version: '3.8'

services:
  app:
    build: .
    container_name: galeria-social-web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=galeria_user
      - DB_HOST=db
      - DB_NAME=galeria_db
      - DB_PASSWORD=galeria_password_segura
      - DB_PORT=5432
      - JWT_SECRET=jwt_secreto_cambiar_en_produccion
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: galeria-social-db
    restart: always
    environment:
      - POSTGRES_USER=galeria_user
      - POSTGRES_PASSWORD=galeria_password_segura
      - POSTGRES_DB=galeria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galeria_user -d galeria_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
